Added namespace to all document API calls
vespa-engine/pyvespa pull request #319
Opened 2022-04-20 16:18 UTC by sephib

In order to solve issue #317  this PR adds namespaces to all Document API calls.

If no namespace is supplied it receives the schema value

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-04-20 19:57 UTC, thigm85 requested changes
I made some remarks. Most importantly, this PR should not break API changes. Please, make sure that there are no integration test failures.

2022-04-20 19:57 UTC, thigm85 commented on vespa/application.py
> +    def _feed_batch_sync(self, namespace: str, schema: str, batch: List[Dict], **kwargs) -> VespaResponse:
1) Let's follow a pattern of adding the `namespace` argument at the end of the parameter list.
2) Why add `**kwargs` here?

2022-04-20 19:57 UTC, thigm85 commented on vespa/application.py
> +    def get_data(self, namespace: str, schema: str, data_id: str) -> VespaResponse:
The changes on this PR should not break the API. Note that in this case `namespace` is a required argument. It should have a default and use schema when not provided.

You can check API breaks by looking at the failed integration tests triggered by this PR.

2022-04-25 08:29 UTC, sephib commented
Hi @thigm85  -
Should I revert to the original test_integration_docker file?

2022-05-05 20:13 UTC, sephib commented
@thigm85 is there anything else that is required to merge the pr?

2022-05-24 06:25 UTC, sephib commented
@thigm85 @kkraune  please let me know if there is anything that is required to merge this PR

2022-05-24 08:15 UTC, thigm85 commented
Hi @sephib, I will take a look at it today

2022-05-24 16:49 UTC, thigm85 commented
Hi @sephib, I would like to push some changes to your PR. Can you grant me permission to do so?

2022-05-26 11:32 UTC, thigm85 commented
Hi @sephib, I am still getting permission denied: 

```
remote: Permission to sephib/pyvespa.git denied to thigm85.
```

2022-05-27 11:25 UTC, thigm85 commented
Since I still lack permission, I created a copy of this PR under pyvespa repo. I will close this one and we can follow the progress here: https://github.com/vespa-engine/pyvespa/pull/337

2022-05-27 11:25 UTC, closed without merging