added user_version param to ApplicationPackage constructor
vespa-engine/pyvespa pull request #421
Opened 2023-01-25 17:04 UTC by JeanExtreme002

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-01-26 11:29 UTC, lesters requested changes
Thanks for this! I feel however that this parameter should not be a top-level argument to the constructor, as this sets a certain configuration setting. There could be many such. What do you think about making this a bit more general, that can support any config setting?

2023-01-26 22:19 UTC, JeanExtreme002 commented
@lesters Done! The only thing I'll do now is fixing the `services_to_text` text fomatting, because for some reason `</config>` is going out from indentation. But everything is already working! :smile:

2023-01-27 12:01 UTC, lesters reviewed
Looks good, but there are test errors?

2023-01-27 15:41 UTC, JeanLoui-Escavador commented
> Looks good, but there are test errors?

Other pull requests had that same problem on Screwdriver/7055/PR:unit-tests

2023-01-31 08:56 UTC, lesters commented on vespa/package.py
> +        """
Unit test fail is related to this. The doctesting fails here. Should be "..." on these lines?

2023-01-31 08:57 UTC, lesters requested changes
Looks ok, but please fix unit test failures.

2023-01-31 18:08 UTC, JeanExtreme002 commented
Sorry for my mistake. It's done! @lesters

2023-01-31 20:05 UTC, lesters approved these changes
LGTM!

2023-01-31 20:05 UTC, merged